# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/home/vagrant", disabled: true
  
  # configure vagrant not to add a keypair for SSH connection
  # Refer https://www.vagrantup.com/docs/vagrantfile/ssh_settings#config-ssh-insert_key for more details.
  config.ssh.insert_key = false

  # first-vm instance
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
	app.vm.network :private_network, ip: "192.168.60.4"
  end

  # second-vm instance
  config.vm.define "app2" do |app|
    app.vm.hostname = "orc-app2"
	app.vm.network :private_network, ip: "192.168.60.5"
  end
end